### ISSUE TITLE
Replace ErrorKind::Ok with proper result types

### ISSUE THREAD

**Issue by str4d** [tarcieri/yubikey-piv.rs#4]

**Comment by str4d** [comment]
@tarcieri do you want a `pub type Result<T> = std::result::Result<T, ErrorKind>` for this, or just stick with the plain syntax?

**Comment by str4d** [comment]
Actually, I'll skip that decision for now.

**Comment by tarcieri** [comment]
I generally prefer not defining a `Result` alias, FWIW
